## Import Library

In [2]:
import cv2
import numpy as np
#202331010_Maulana Hasbi Nofelin

## Membaca Citra

In [3]:
citra = cv2.imread('semangka.jpg')
#202331010_Maulana Hasbi Nofelin

In [4]:
cv2.imshow("citra asli", citra)
cv2.waitKey()
cv2.destroyAllWindows()

## Dimensi Citra

In [5]:
print(citra.shape)
print(citra.dtype)
#202331010_Maulana Hasbi Nofelin

(640, 591, 3)
uint8


## Splitting Citra RGB/BGR

In [7]:
b = citra[:,:,0]
g = citra[:,:,1]
r = citra[:,:,2]
#202331010_Maulana Hasbi Nofelin

## RGB to Grayscale

In [8]:
panjang = len(citra)
lebar = len(citra[0])

citra_gray = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        citra_gray[i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 * b[i,j] #merah= 29,89% ; hijau 58,7% ; biru = 11,41%

citra_gray = citra_gray.astype(np.uint8)

cv2.imshow("citra gray", citra_gray)
cv2.waitKey()
cv2.destroyAllWindows()
#202331010_Maulana Hasbi Nofelin

In [11]:
print(citra)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [12]:
print(citra_gray)

[[254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 ...
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]]


## Grayscale to Binary

In [9]:
panjang = len(citra)
lebar = len(citra[0])

ambang = 90

citra_biner = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        if citra_gray[i,j] >= ambang:
            citra_biner[i,j] = 1 #putih
        else:
            citra_biner[i,j] = 0 #hitam

cv2.imshow("citra binary", citra_biner)
cv2.waitKey()
cv2.destroyAllWindows()
#202331010_Maulana Hasbi Nofelin

In [13]:
print(citra_biner)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [10]:
print(citra_biner[50,50])
#202331010_Maulana Hasbi Nofelin

1.0
